In [4]:
import pandas as pd
import numpy as np

In [7]:
df = pd.read_csv("../data/processed/feature_engineered_data.csv")

In [8]:
ship_mode_summary = (
    df.groupby("Ship Mode")
      .agg(
          Total_Shipments=("Order ID", "count"),
          Average_Lead_Time=("Shipping Lead Time", "mean"),
          Average_Sales=("Sales", "mean"),
          Average_Cost=("Cost", "mean")
      )
      .reset_index()
)

In [9]:
ship_mode_summary

,Ship Mode,Total_Shipments,Average_Lead_Time,Average_Sales,Average_Cost
0,First Class,1548,8.091731,13.772216,4.721124
1,Same Day,547,7.989031,13.004881,4.411225
2,Second Class,1979,7.998484,14.077928,4.827539
3,Standard Class,6120,7.969118,13.969011,4.749328

In [10]:
delay_summary = (
    df.groupby("Ship Mode")["Delay Flag"]
      .apply(lambda x: (x == "Delayed").mean() * 100)
      .reset_index(name="Delay_Percentage")
)

In [11]:
ship_mode_summary = ship_mode_summary.merge(
    delay_summary,
    on="Ship Mode"
)

In [12]:
ship_mode_summary

,Ship Mode,Total_Shipments,Average_Lead_Time,Average_Sales,Average_Cost,Delay_Percentage
0,First Class,1548,8.091731,13.772216,4.721124,53.617571
1,Same Day,547,7.989031,13.004881,4.411225,53.016453
2,Second Class,1979,7.998484,14.077928,4.827539,53.562405
3,Standard Class,6120,7.969118,13.969011,4.749328,52.924837

In [13]:
fastest_mode = ship_mode_summary.sort_values(
    by="Average_Lead_Time"
)

fastest_mode.head()

,Ship Mode,Total_Shipments,Average_Lead_Time,Average_Sales,Average_Cost,Delay_Percentage
3,Standard Class,6120,7.969118,13.969011,4.749328,52.924837
1,Same Day,547,7.989031,13.004881,4.411225,53.016453
2,Second Class,1979,7.998484,14.077928,4.827539,53.562405
0,First Class,1548,8.091731,13.772216,4.721124,53.617571

In [14]:
highest_delay = ship_mode_summary.sort_values(
    by="Delay_Percentage",
    ascending=False
)

highest_delay.head()

,Ship Mode,Total_Shipments,Average_Lead_Time,Average_Sales,Average_Cost,Delay_Percentage
0,First Class,1548,8.091731,13.772216,4.721124,53.617571
2,Second Class,1979,7.998484,14.077928,4.827539,53.562405
1,Same Day,547,7.989031,13.004881,4.411225,53.016453
3,Standard Class,6120,7.969118,13.969011,4.749328,52.924837

In [15]:
ship_mode_summary.to_csv(
    "../data/processed/ship_mode_summary.csv",
    index=False
)