In [10]:
import pandas as pd
import numpy as np

In [12]:
import pandas as pd

df_clean = pd.read_csv("../data/processed/feature_engineered_data.csv")

In [15]:
df_clean.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Country/Region,City,State/Province,Postal Code,...,Units,Gross Profit,Cost,Shipping Lead Time,Delay Flag,Factory,Factory Latitude,Factory Longitude,Factory_State_Route,Factory_Region_Route
0,1,US-2021-103800-CHO-MIL-31000,2024-01-03,2024-01-10,Standard Class,103800,United States,Houston,Texas,77095,...,2,4.22,2.28,7,On Time,Wicked Choccy's,32.076176,-81.088371,Wicked Choccy's → Texas,Wicked Choccy's → Interior
1,2,US-2021-112326-CHO-TRI-54000,2024-01-04,2024-01-08,Standard Class,112326,United States,Naperville,Illinois,60540,...,2,4.90,2.60,4,On Time,Wicked Choccy's,32.076176,-81.088371,Wicked Choccy's → Illinois,Wicked Choccy's → Interior
2,3,US-2021-112326-CHO-NUT-13000,2024-01-04,2024-01-17,Standard Class,112326,United States,Naperville,Illinois,60540,...,3,7.47,3.00,13,Delayed,Lot's O' Nuts,32.881893,-111.768036,Lot's O' Nuts → Illinois,Lot's O' Nuts → Interior
3,4,US-2021-112326-CHO-SCR-58000,2024-01-04,2024-01-19,Standard Class,112326,United States,Naperville,Illinois,60540,...,3,7.50,3.30,15,Delayed,Lot's O' Nuts,32.881893,-111.768036,Lot's O' Nuts → Illinois,Lot's O' Nuts → Interior
4,5,US-2021-141817-CHO-TRI-54000,2024-01-05,2024-01-16,Standard Class,141817,United States,Philadelphia,Pennsylvania,19143,...,3,7.35,3.90,11,Delayed,Wicked Choccy's,32.076176,-81.088371,Wicked Choccy's → Pennsylvania,Wicked Choccy's → Atlantic

In [17]:
# info or summary of factory by state
route_state = (
    df_clean.groupby("Factory_State_Route")
      .agg(
          Total_Shipments=("Order ID", "count"),
          Average_Lead_Time=("Shipping Lead Time", "mean"),
          Lead_Time_Variability=("Shipping Lead Time", "std")
      )
      .reset_index()
)

In [18]:
route_state.head(10)

,Factory_State_Route,Total_Shipments,Average_Lead_Time,Lead_Time_Variability
0,Lot's O' Nuts → Alabama,34,8.058824,4.867587
1,Lot's O' Nuts → Alberta,16,8.312500,4.922313
2,Lot's O' Nuts → Arizona,111,6.873874,4.365395
3,Lot's O' Nuts → Arkansas,31,8.548387,4.595931
4,Lot's O' Nuts → British Columbia,18,7.777778,4.784233
5,Lot's O' Nuts → California,1125,7.881778,4.285131
6,Lot's O' Nuts → Colorado,103,8.271845,4.659366
7,Lot's O' Nuts → Connecticut,47,8.276596,4.052386
8,Lot's O' Nuts → Delaware,43,7.581395,4.294141
9,Lot's O' Nuts → District of Columbia,8,8.500000,4.140393

In [19]:
# save summary
route_state.to_csv(
    "../data/processed/route_state_summary.csv",
    index=False
)

In [21]:
df_clean.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Country/Region,City,State/Province,Postal Code,...,Units,Gross Profit,Cost,Shipping Lead Time,Delay Flag,Factory,Factory Latitude,Factory Longitude,Factory_State_Route,Factory_Region_Route
0,1,US-2021-103800-CHO-MIL-31000,2024-01-03,2024-01-10,Standard Class,103800,United States,Houston,Texas,77095,...,2,4.22,2.28,7,On Time,Wicked Choccy's,32.076176,-81.088371,Wicked Choccy's → Texas,Wicked Choccy's → Interior
1,2,US-2021-112326-CHO-TRI-54000,2024-01-04,2024-01-08,Standard Class,112326,United States,Naperville,Illinois,60540,...,2,4.90,2.60,4,On Time,Wicked Choccy's,32.076176,-81.088371,Wicked Choccy's → Illinois,Wicked Choccy's → Interior
2,3,US-2021-112326-CHO-NUT-13000,2024-01-04,2024-01-17,Standard Class,112326,United States,Naperville,Illinois,60540,...,3,7.47,3.00,13,Delayed,Lot's O' Nuts,32.881893,-111.768036,Lot's O' Nuts → Illinois,Lot's O' Nuts → Interior
3,4,US-2021-112326-CHO-SCR-58000,2024-01-04,2024-01-19,Standard Class,112326,United States,Naperville,Illinois,60540,...,3,7.50,3.30,15,Delayed,Lot's O' Nuts,32.881893,-111.768036,Lot's O' Nuts → Illinois,Lot's O' Nuts → Interior
4,5,US-2021-141817-CHO-TRI-54000,2024-01-05,2024-01-16,Standard Class,141817,United States,Philadelphia,Pennsylvania,19143,...,3,7.35,3.90,11,Delayed,Wicked Choccy's,32.076176,-81.088371,Wicked Choccy's → Pennsylvania,Wicked Choccy's → Atlantic

In [22]:
route_summary = pd.read_csv("../data/processed/route_state_summary.csv")

In [23]:
route_summary.head()

,Factory_State_Route,Total_Shipments,Average_Lead_Time,Lead_Time_Variability
0,Lot's O' Nuts → Alabama,34,8.058824,4.867587
1,Lot's O' Nuts → Alberta,16,8.312500,4.922313
2,Lot's O' Nuts → Arizona,111,6.873874,4.365395
3,Lot's O' Nuts → Arkansas,31,8.548387,4.595931
4,Lot's O' Nuts → British Columbia,18,7.777778,4.784233

In [24]:
route_summary = route_summary.sort_values(
    by="Average_Lead_Time",
    ascending=True
)

In [25]:
route_summary["Route_Rank"] = range(
    1,
    len(route_summary) + 1
)

In [26]:
top10_routes = route_summary.head(10)

top10_routes

,Factory_State_Route,Total_Shipments,Average_Lead_Time,Lead_Time_Variability,Route_Rank
91,Secret Factory → Utah,1,1.0,NaN,1
131,The Other Factory → Oregon,2,1.5,0.707107,2
108,Sugar Shack → Tennessee,1,2.0,NaN,3
78,Secret Factory → New Hampshire,1,2.0,NaN,4
134,The Other Factory → South Carolina,1,2.0,NaN,5
75,Secret Factory → Mississippi,1,2.0,NaN,6
74,Secret Factory → Minnesota,1,2.0,NaN,7
115,The Other Factory → Connecticut,2,3.0,2.828427,8
107,Sugar Shack → Rhode Island,1,3.0,NaN,9
129,The Other Factory → North Carolina,1,3.0,NaN,10

In [27]:
bottom10_routes = route_summary.tail(10)

bottom10_routes

,Factory_State_Route,Total_Shipments,Average_Lead_Time,Lead_Time_Variability,Route_Rank
88,Secret Factory → South Carolina,1,12.000000,NaN,187
58,Secret Factory → Alberta,2,12.000000,4.242641,188
185,Wicked Choccy's → Saskatchewan,2,12.500000,2.121320,189
114,The Other Factory → Colorado,2,12.500000,0.707107,190
51,Lot's O' Nuts → Vermont,5,12.600000,3.781534,191
63,Secret Factory → Connecticut,1,13.000000,NaN,192
106,Sugar Shack → Pennsylvania,3,13.333333,1.527525,193
125,The Other Factory → Nevada,1,14.000000,NaN,194
103,Sugar Shack → New Jersey,1,14.000000,NaN,195
124,The Other Factory → Missouri,1,15.000000,NaN,196

In [28]:
top10_routes.to_csv(
    "../data/processed/top_10_routes.csv",
    index=False
)

bottom10_routes.to_csv(
    "../data/processed/bottom_10_routes.csv",
    index=False
)

In [29]:
route_summary = df_clean.groupby("Factory_State_Route").agg(
    Average_Lead_Time=("Shipping Lead Time", "mean"),
    Route_Volume=("Factory_State_Route", "count")
).reset_index()

In [30]:
route_summary.head()

                Factory_State_Route  Average_Lead_Time  Route_Volume
0           Lot's O' Nuts → Alabama           8.058824            34
1           Lot's O' Nuts → Alberta           8.312500            16
2           Lot's O' Nuts → Arizona           6.873874           111
3          Lot's O' Nuts → Arkansas           8.548387            31
4  Lot's O' Nuts → British Columbia           7.777778            18

In [31]:
route_summary.to_csv(
    "../data/processed/route_state_summary.csv",
    index=False
)

In [32]:
pd.read_csv("../data/processed/route_state_summary.csv").head()

                Factory_State_Route  Average_Lead_Time  Route_Volume
0           Lot's O' Nuts → Alabama           8.058824            34
1           Lot's O' Nuts → Alberta           8.312500            16
2           Lot's O' Nuts → Arizona           6.873874           111
3          Lot's O' Nuts → Arkansas           8.548387            31
4  Lot's O' Nuts → British Columbia           7.777778            18

In [33]:
max_time = route_summary["Average_Lead_Time"].max()
min_time = route_summary["Average_Lead_Time"].min()

route_summary["Route_Efficiency_Score"] = (
    100 * (max_time - route_summary["Average_Lead_Time"])
    / (max_time - min_time)
)

In [34]:
route_summary.head()

,Factory_State_Route,Average_Lead_Time,Route_Volume,Route_Efficiency_Score
0,Lot's O' Nuts → Alabama,8.058824,34,49.579832
1,Lot's O' Nuts → Alberta,8.312500,16,47.767857
2,Lot's O' Nuts → Arizona,6.873874,111,58.043758
3,Lot's O' Nuts → Arkansas,8.548387,31,46.082949
4,Lot's O' Nuts → British Columbia,7.777778,18,51.587302

In [35]:
route_summary.to_csv(
    "../data/processed/route_state_summary.csv",
    index=False
)

In [36]:
route_summary.head()

,Factory_State_Route,Average_Lead_Time,Route_Volume,Route_Efficiency_Score
0,Lot's O' Nuts → Alabama,8.058824,34,49.579832
1,Lot's O' Nuts → Alberta,8.312500,16,47.767857
2,Lot's O' Nuts → Arizona,6.873874,111,58.043758
3,Lot's O' Nuts → Arkansas,8.548387,31,46.082949
4,Lot's O' Nuts → British Columbia,7.777778,18,51.587302